micronaut:
  server:
    port: 8087
  config-client:
    enabled: true
endpoints:
  env:
    sensitive: false
    enabled: true
  refresh:
    sensitive: false
  health:
    details-visible: ANONYMOUS